address: "0.0.0.0"
port: 9109
metricsPath: "/metrics"
log:
  level: "debug"
  log_path: "/var/log/uos-exporter/squid-exporter.log"
# Squid配置文件路径 - 用于监控squid配置文件的指标
squidConfigPath: "/etc/squid/squid.conf"
squidConfigDir: "/etc/squid/"
squid:
  hostname: "localhost"
  port: 3128
  login: ""
  password: ""
  extractTimes: true
