address: "127.0.0.1"
port: 9109
metricsPath: "/metrics"
log:
  level: "debug"
  log_path: "/var/log/uos-exporter/squid-exporter.log"
squid:
  hostname: "localhost"
  port: 3128
  login: ""
  password: ""
  extractTimes: true
